baseURL = "https://gohugo.io/"
title = "Modcast Podcast"
author = "Modcast Podcast"
copyright = "Copyright © 2021"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "casper"

[params]
  twitter = "https://twitter.com/modcastpod"
  description = "A podcast by moderators for moderators!"
  mainSections = ["posts"]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    identifier = "contact"
    name = "Contact Us"
    title = "Contact Us"
    url = "/contact-us"
    weight = -100

  [[menu.main]]
    identifier = "listen"
    name = "Listen"
    title = "Listen"
    url = "/listen"
    weight = -90

[taxonomies]
category = "categories"
tag = "tags"
